// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwery3Ji7GeoDJYrB4ieQMiFAgUMCssF8',
    appId: '1:988815369913:web:a634ea9ecb8140d5951d68',
    messagingSenderId: '988815369913',
    projectId: 'traitlens',
    authDomain: 'traitlens.firebaseapp.com',
    storageBucket: 'traitlens.firebasestorage.app',
    measurementId: 'G-F2JVLKQH4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1WteXwEGvRIintD2Ut_knYdleTBfDbTM',
    appId: '1:988815369913:android:dc0018b0ff4d1985951d68',
    messagingSenderId: '988815369913',
    projectId: 'traitlens',
    storageBucket: 'traitlens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA62F5vdaWm5b6iQv9e9VxF8kgbewvf8Vk',
    appId: '1:988815369913:ios:7bb5d0ecbc01261d951d68',
    messagingSenderId: '988815369913',
    projectId: 'traitlens',
    storageBucket: 'traitlens.firebasestorage.app',
    androidClientId: '988815369913-iuuarllog4jcqtek9dl5b9j198fo7p0f.apps.googleusercontent.com',
    iosClientId: '988815369913-rn2m6qrta2ct70rlcdr9gbio6cv5hao6.apps.googleusercontent.com',
    iosBundleId: 'com.example.traitLensAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA62F5vdaWm5b6iQv9e9VxF8kgbewvf8Vk',
    appId: '1:988815369913:ios:7bb5d0ecbc01261d951d68',
    messagingSenderId: '988815369913',
    projectId: 'traitlens',
    storageBucket: 'traitlens.firebasestorage.app',
    androidClientId: '988815369913-iuuarllog4jcqtek9dl5b9j198fo7p0f.apps.googleusercontent.com',
    iosClientId: '988815369913-rn2m6qrta2ct70rlcdr9gbio6cv5hao6.apps.googleusercontent.com',
    iosBundleId: 'com.example.traitLensAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwery3Ji7GeoDJYrB4ieQMiFAgUMCssF8',
    appId: '1:988815369913:web:0360264be1111fcf951d68',
    messagingSenderId: '988815369913',
    projectId: 'traitlens',
    authDomain: 'traitlens.firebaseapp.com',
    storageBucket: 'traitlens.firebasestorage.app',
    measurementId: 'G-BG3D6EVNXX',
  );
}
